### PR TITLE
Error Installing agpy package

### PR DESCRIPTION
**Pull request by keflavich**
Hello! I'm attempting to install your python package and when I run python setup.py install in the root directory I'm getting the following error:

error: package directory 'contributed' does not exist

Any idea where this package is?

Thanks so much :)

### CODE REVIEW

**Comment by keflavich** [comment]
@catherinezucker you've found a bug!  The attached patch should fix it.

However, what part of agpy are you planning to use?  Most of the functionality has now been migrated to other packages; you may be better served using one of those (and I may be able to help direct you to the right ones)

**Comment by catherinezucker** [comment]
At the moment, I just need the kinematic distance kdist module. What would you recommend? Thanks so much!

Also, I'm Cara Battersby's student at Harvard, who mentioned that you were both advised by John Bally at Colorado!  Nice to finally meet you!

**Comment by keflavich** [comment]
kdist is available in agpy or in its own standalone module:
https://github.com/keflavich/kdist

I know of your Milky Way bones work!  Nice to be in touch.

**Comment by catherinezucker** [comment]
Great, thanks! I'll just download it on its own.

**Pull request merged**
